[2019-02-25 11:11:29,693][Thread-1:130944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: showMainPage() missing 1 required positional argument: 'path'
[2019-02-25 11:20:39,161][Thread-3:133920][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/css/prism.css]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 21, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './assets/css/prism.css'
[2019-02-25 11:20:39,219][Thread-1:133888][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/css/main.css]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 21, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './assets/css/main.css'
[2019-02-25 11:20:39,454][Thread-5:133936][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/getpv.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/getpv.js'
[2019-02-25 11:20:39,524][Thread-4:133924][task_id:django.request][log.py:228][ERROR][Internal Server Error: /images/cf915d_1.jpg]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 35, in showImages
    with open('./images/'+path, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/cf915d_1.jpg'
[2019-02-25 11:20:39,591][Thread-7:133944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/util.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/util.js'
[2019-02-25 11:20:39,594][Thread-6:133940][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/skel.min.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/skel.min.js'
[2019-02-25 11:20:39,952][Thread-1:133888][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/prism.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/prism.js'
[2019-02-25 11:20:40,001][Thread-5:133936][task_id:django.request][log.py:228][ERROR][Internal Server Error: /images/friend_01.jpg]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 35, in showImages
    with open('./images/'+path, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/friend_01.jpg'
[2019-02-25 11:20:40,012][Thread-8:134012][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/main.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/main.js'
[2019-02-25 11:20:40,085][Thread-7:133944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /images/pic09.jpg]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 35, in showImages
    with open('./images/'+path, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/pic09.jpg'
[2019-02-25 11:20:40,112][Thread-4:133924][task_id:django.request][log.py:228][ERROR][Internal Server Error: /images/friend_02.jpg]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 35, in showImages
    with open('./images/'+path, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/friend_02.jpg'
[2019-02-25 11:20:40,166][Thread-6:133940][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/skel.min.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/skel.min.js'
[2019-02-25 11:20:40,243][Thread-6:133940][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/util.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/util.js'
[2019-02-25 11:20:40,349][Thread-6:133940][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/main.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/main.js'
[2019-02-25 11:20:40,396][Thread-6:133940][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/js/prism.js]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 26, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './static/js/prism.js'
[2019-02-25 11:20:43,976][Thread-6:133940][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/css/main.css]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 21, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './assets/css/main.css'
[2019-02-25 11:20:44,001][Thread-4:133924][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/css/prism.css]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\Website\staticApp\views.py", line 21, in showAssets
    with open('./assets/' + path, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './assets/css/prism.css'
[2019-02-25 11:22:43,047][Thread-4:133720][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/fonts/fontawesome-webfont.woff2]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view staticApp.views.showAssets didn't return an HttpResponse object. It returned None instead.
[2019-02-25 11:22:43,275][Thread-4:133720][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/fonts/fontawesome-webfont.woff]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view staticApp.views.showAssets didn't return an HttpResponse object. It returned None instead.
[2019-02-25 11:22:43,351][Thread-4:133720][task_id:django.request][log.py:228][ERROR][Internal Server Error: /assets/fonts/fontawesome-webfont.ttf]
Traceback (most recent call last):
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Project\Website\venv\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view staticApp.views.showAssets didn't return an HttpResponse object. It returned None instead.
